// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupRequestMessage struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequestMessage) Reset()         { *m = SignupRequestMessage{} }
func (m *SignupRequestMessage) String() string { return proto.CompactTextString(m) }
func (*SignupRequestMessage) ProtoMessage()    {}
func (*SignupRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *SignupRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequestMessage.Unmarshal(m, b)
}
func (m *SignupRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequestMessage.Marshal(b, m, deterministic)
}
func (m *SignupRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequestMessage.Merge(m, src)
}
func (m *SignupRequestMessage) XXX_Size() int {
	return xxx_messageInfo_SignupRequestMessage.Size(m)
}
func (m *SignupRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequestMessage proto.InternalMessageInfo

func (m *SignupRequestMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequestMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequestMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupResponseMessage struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponseMessage) Reset()         { *m = SignupResponseMessage{} }
func (m *SignupResponseMessage) String() string { return proto.CompactTextString(m) }
func (*SignupResponseMessage) ProtoMessage()    {}
func (*SignupResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *SignupResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponseMessage.Unmarshal(m, b)
}
func (m *SignupResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponseMessage.Marshal(b, m, deterministic)
}
func (m *SignupResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponseMessage.Merge(m, src)
}
func (m *SignupResponseMessage) XXX_Size() int {
	return xxx_messageInfo_SignupResponseMessage.Size(m)
}
func (m *SignupResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponseMessage proto.InternalMessageInfo

func (m *SignupResponseMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequestMessage struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequestMessage) Reset()         { *m = LoginRequestMessage{} }
func (m *LoginRequestMessage) String() string { return proto.CompactTextString(m) }
func (*LoginRequestMessage) ProtoMessage()    {}
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *LoginRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequestMessage.Unmarshal(m, b)
}
func (m *LoginRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequestMessage.Marshal(b, m, deterministic)
}
func (m *LoginRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequestMessage.Merge(m, src)
}
func (m *LoginRequestMessage) XXX_Size() int {
	return xxx_messageInfo_LoginRequestMessage.Size(m)
}
func (m *LoginRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequestMessage proto.InternalMessageInfo

func (m *LoginRequestMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequestMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponseMessage struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponseMessage) Reset()         { *m = LoginResponseMessage{} }
func (m *LoginResponseMessage) String() string { return proto.CompactTextString(m) }
func (*LoginResponseMessage) ProtoMessage()    {}
func (*LoginResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *LoginResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponseMessage.Unmarshal(m, b)
}
func (m *LoginResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponseMessage.Marshal(b, m, deterministic)
}
func (m *LoginResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponseMessage.Merge(m, src)
}
func (m *LoginResponseMessage) XXX_Size() int {
	return xxx_messageInfo_LoginResponseMessage.Size(m)
}
func (m *LoginResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponseMessage proto.InternalMessageInfo

func (m *LoginResponseMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Admin                bool     `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type CreateUserReq struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Admin                bool     `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{5}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserReq) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ResponseMsg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMsg) Reset()         { *m = ResponseMsg{} }
func (m *ResponseMsg) String() string { return proto.CompactTextString(m) }
func (*ResponseMsg) ProtoMessage()    {}
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{7}
}

func (m *ResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMsg.Unmarshal(m, b)
}
func (m *ResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMsg.Marshal(b, m, deterministic)
}
func (m *ResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMsg.Merge(m, src)
}
func (m *ResponseMsg) XXX_Size() int {
	return xxx_messageInfo_ResponseMsg.Size(m)
}
func (m *ResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMsg proto.InternalMessageInfo

func (m *ResponseMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetUsersResp struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResp) Reset()         { *m = GetUsersResp{} }
func (m *GetUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetUsersResp) ProtoMessage()    {}
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{8}
}

func (m *GetUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResp.Unmarshal(m, b)
}
func (m *GetUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResp.Marshal(b, m, deterministic)
}
func (m *GetUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResp.Merge(m, src)
}
func (m *GetUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetUsersResp.Size(m)
}
func (m *GetUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResp proto.InternalMessageInfo

func (m *GetUsersResp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{9}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Admin                bool     `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdRequest) Reset()         { *m = GetByIdRequest{} }
func (m *GetByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIdRequest) ProtoMessage()    {}
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{10}
}

func (m *GetByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdRequest.Unmarshal(m, b)
}
func (m *GetByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdRequest.Merge(m, src)
}
func (m *GetByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIdRequest.Size(m)
}
func (m *GetByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdRequest proto.InternalMessageInfo

func (m *GetByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByIdRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetByIdRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetByIdRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetByIdRequest) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{11}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResp) Reset()         { *m = DeleteUserResp{} }
func (m *DeleteUserResp) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResp) ProtoMessage()    {}
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{12}
}

func (m *DeleteUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResp.Unmarshal(m, b)
}
func (m *DeleteUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResp.Marshal(b, m, deterministic)
}
func (m *DeleteUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResp.Merge(m, src)
}
func (m *DeleteUserResp) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResp.Size(m)
}
func (m *DeleteUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResp proto.InternalMessageInfo

func (m *DeleteUserResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*SignupRequestMessage)(nil), "user.SignupRequestMessage")
	proto.RegisterType((*SignupResponseMessage)(nil), "user.SignupResponseMessage")
	proto.RegisterType((*LoginRequestMessage)(nil), "user.LoginRequestMessage")
	proto.RegisterType((*LoginResponseMessage)(nil), "user.LoginResponseMessage")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserReq)(nil), "user.CreateUserReq")
	proto.RegisterType((*Empty)(nil), "user.Empty")
	proto.RegisterType((*ResponseMsg)(nil), "user.ResponseMsg")
	proto.RegisterType((*GetUsersResp)(nil), "user.GetUsersResp")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetByIdRequest)(nil), "user.GetByIdRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResp)(nil), "user.DeleteUserResp")
}

func init() {
	proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504)
}

var fileDescriptor_744bf7a47b381504 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xe3, 0xb8, 0x84, 0x09, 0x8d, 0xe8, 0x34, 0x55, 0x8d, 0x91, 0xc0, 0x5a, 0x2e, 0xbd,
	0x90, 0x94, 0x22, 0x81, 0xc4, 0x09, 0xb5, 0x20, 0x84, 0x44, 0x25, 0x94, 0x2a, 0x17, 0x6e, 0x2e,
	0x1e, 0xac, 0x95, 0x62, 0x7b, 0xeb, 0x71, 0x40, 0xe5, 0xcc, 0x47, 0xf0, 0xb9, 0x68, 0x77, 0xed,
	0xc4, 0x36, 0x69, 0xa5, 0x5e, 0x7a, 0xcb, 0xe4, 0xbd, 0xd9, 0x79, 0x7a, 0xf3, 0xc6, 0xb0, 0xab,
	0x8a, 0xfc, 0x87, 0x5c, 0xd2, 0x54, 0x15, 0x79, 0x99, 0xe3, 0x60, 0xc5, 0x54, 0x88, 0x18, 0x26,
	0x17, 0x32, 0xc9, 0x56, 0x6a, 0x4e, 0x57, 0x2b, 0xe2, 0xf2, 0x9c, 0x98, 0xa3, 0x84, 0x30, 0x80,
	0xa1, 0xc6, 0xb3, 0x28, 0x25, 0xdf, 0x09, 0x9d, 0xa3, 0x87, 0xf3, 0x75, 0x8d, 0x13, 0xf0, 0x28,
	0x8d, 0xe4, 0xd2, 0xef, 0x1b, 0xc0, 0x16, 0xba, 0x43, 0x45, 0xcc, 0xbf, 0xf2, 0x22, 0xf6, 0x5d,
	0xdb, 0x51, 0xd7, 0xe2, 0x2d, 0x1c, 0xd4, 0x53, 0x58, 0xe5, 0x19, 0x53, 0x3d, 0xe6, 0x19, 0x18,
	0x19, 0x66, 0xc4, 0xe8, 0x04, 0xa6, 0xba, 0x98, 0x2e, 0x98, 0x8a, 0xb9, 0x95, 0x77, 0x0e, 0xfb,
	0x5f, 0xf2, 0x44, 0x66, 0x77, 0x50, 0xd7, 0xd4, 0xd1, 0xef, 0xe8, 0x78, 0x03, 0x93, 0xea, 0xb9,
	0xbb, 0xc9, 0xf8, 0x0d, 0x03, 0x5d, 0xe1, 0x18, 0xfa, 0x32, 0xae, 0x26, 0xf6, 0x65, 0x7c, 0xb3,
	0x13, 0x6b, 0x75, 0xee, 0x2d, 0xea, 0x06, 0x6d, 0x75, 0xfa, 0xb5, 0x28, 0x4e, 0x65, 0xe6, 0x7b,
	0xa1, 0x73, 0x34, 0x9c, 0xdb, 0x42, 0x30, 0xec, 0x9e, 0x15, 0x14, 0x95, 0x64, 0xf4, 0xd0, 0xd5,
	0xbd, 0x0c, 0x7d, 0x00, 0xde, 0xc7, 0x54, 0x95, 0xd7, 0xe2, 0x39, 0x8c, 0xd6, 0x66, 0x71, 0x82,
	0x8f, 0xc1, 0x4d, 0x39, 0xa9, 0x1c, 0xd0, 0x3f, 0xc5, 0x31, 0x3c, 0xfa, 0x44, 0xa5, 0xd6, 0xc6,
	0x9a, 0x88, 0x21, 0x78, 0x7a, 0x2e, 0xfb, 0x4e, 0xe8, 0x76, 0xbc, 0xb4, 0x80, 0x08, 0x61, 0x5c,
	0x75, 0x54, 0x5b, 0xed, 0xda, 0x2a, 0xfe, 0x38, 0x86, 0x72, 0x7a, 0xfd, 0x39, 0xbe, 0x81, 0x72,
	0x2f, 0x26, 0xbc, 0x80, 0xbd, 0x0f, 0xb4, 0xa4, 0xb5, 0xf3, 0x5b, 0xb5, 0x86, 0x30, 0x6e, 0x92,
	0x58, 0x75, 0x19, 0x27, 0x7f, 0x5d, 0x18, 0x7f, 0xb5, 0xa7, 0x77, 0x41, 0xc5, 0x4f, 0xf9, 0x9d,
	0xf0, 0x0c, 0x76, 0xf4, 0x3d, 0x2c, 0x14, 0x06, 0xd6, 0x9f, 0x6d, 0x37, 0x18, 0x3c, 0x6d, 0x63,
	0xad, 0xc8, 0x8a, 0x1e, 0xbe, 0x07, 0xcf, 0x84, 0x19, 0x9f, 0x58, 0xde, 0x96, 0x43, 0x09, 0x82,
	0x16, 0xd4, 0x7d, 0x61, 0x06, 0xb0, 0x89, 0x16, 0xee, 0x5b, 0x6e, 0x2b, 0x6c, 0x41, 0x63, 0x7f,
	0xa2, 0x87, 0x2f, 0x61, 0x58, 0x2f, 0x1b, 0x47, 0x16, 0x31, 0x31, 0x09, 0xd0, 0x16, 0xcd, 0x24,
	0x88, 0x1e, 0xbe, 0x82, 0x51, 0xf5, 0x8f, 0x5e, 0x25, 0x4e, 0x5a, 0xa4, 0x4a, 0x69, 0x67, 0xc2,
	0x31, 0xc0, 0x42, 0xc5, 0xb5, 0xa4, 0x4d, 0x47, 0x23, 0x0b, 0x9d, 0x8e, 0x77, 0x00, 0x9b, 0x05,
	0xe0, 0xa1, 0xc5, 0xfe, 0xdb, 0x5b, 0xb0, 0x67, 0x81, 0x46, 0x98, 0x45, 0xef, 0xf4, 0xf0, 0xdb,
	0xc1, 0x4c, 0x66, 0xa5, 0x4e, 0xc8, 0x72, 0xc6, 0x76, 0x39, 0x3c, 0x53, 0x97, 0x97, 0x3b, 0xe6,
	0x1b, 0xf9, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x3e, 0x67, 0x49, 0x34, 0x05, 0x00,
	0x00,
}
